version: '3.8'

services:
  log-voyager:
    image: nginx:1.26.2
    container_name: log_voyager
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
